[package]
name = "systest"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
jni-sys.workspace = true
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"

[features]
jni19 = []
jni20 = []
jni21 = []
jni24 = []
